version: "3.4"
services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
    command: [ "redis-server" ]
    container_name: redis
    restart: unless-stopped
  uploader:    
    container_name: uploader
    build:      
      context: ./
      dockerfile: ./Dockerfile_Uploader
    depends_on: [ redis ]        
    ports:
      - "8081:80"
    expose:
      - "80"
  converter:    
    container_name: converter
    build:      
      context: ./
      dockerfile: ./Dockerfile_Converter
    depends_on: [ redis ]        
    ports:
      - "8082:80"